FROM rust:1.59.0-alpine as builder
RUN apk add libc-dev openssl-dev

WORKDIR /src
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY src src
RUN RUSTFLAGS="-C target-feature=-crt-static" cargo build --release

FROM alpine:3.15.0
RUN apk add libgcc libssl1.1
COPY --from=builder /src/target/release/client /client
ENTRYPOINT ["/client"]
