apiVersion: apps/v1
kind: Deployment
metadata:
  name: helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helper
  template:
    metadata:
      labels:
        app: helper
    spec:
      containers:
      - name: helper
        image: localhost/ppm-prototype-helper
        imagePullPolicy: IfNotPresent
        env:
        - name: RUST_LOG
          value: debug
        ports:
        - containerPort: 8081
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.config/ppm-prototype
          name: config-volume
          readOnly: true
      volumes:
      - configMap:
          name: ppm-config
        name: config-volume
